export const EMPLOYEE_LIST_REQ = 'EMPLOYEE_LIST_REQ';
export const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS';
export const EMPLOYEE_LIST_ERR = 'EMPLOYEE_LIST_ERR';

export const EMPLOYEE_ID_REQ = 'EMPLOYEE_ID_REQ';
export const EMPLOYEE_ID_SUCCESS = 'EMPLOYEE_ID_SUCCESS';
export const EMPLOYEE_ID_ERR = 'EMPLOYEE_ID_ERR';