export const USER_SIGNUP_REQ = 'USER_SIGNUP_REQ';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_ERR = 'USER_SIGNUP_ERR';

export const USER_LOGIN_REQ = 'USER_LOGIN_REQ';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERR = 'USER_LOGIN_ERR';